
title: Geological Tactile Image Repository

description: >- # this means to ignore newlines until "baseurl:"
  An image repository for tactile graphics used in geosciences education.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass
    - node_modules

data_image_file: tactile_images.csv

keep_files:
  - assets/javascripts/index.bundle.js
